apt install -y php7.4-mysqli
apt install -y php7.4-gd
apt install -y php7.4-mysql
apt install -y php7.4-opcache
apt install -y php7.4-apcu
apt install -y php7.4-exif
apt install -y php7.4-intl
apt install -y php7.4-mbstring
apt install -y php7.4-zip
apt install -y php7.4-xml
apt install -y php7.4-curl